SELECT * 
FROM COMPOSICIONPRODUCTO CO
LEFT JOIN INGREDIENTEPRODUCCION IP ON CO.IDCOMPOSICIONPRODUCTO = IP.IDCOMPOSICIONPRODUCTO;



-- 26/02/2015
-- PRIMARY, FOREIGN KEYS: INGREDIENTEPRODUCCION
ALTER TABLE COMPOSICIONPRODUCTO     ADD CONSTRAINT PK_COMPOSICIONPRODUCTO       PRIMARY KEY (IDCOMPOSICIONPRODUCTO);
ALTER TABLE INGREDIENTEPRODUCCION   ADD CONSTRAINT PK_INGREDIENTEPRODUCCION     PRIMARY KEY (IDINGREDIENTEPRODUCCION);
ALTER TABLE METAPRODUCTOPRODUCCION  ADD CONSTRAINT PK_METAPRODUCTOPRODUCCION    PRIMARY KEY (IDMETAPRODUCTOPRODUCCION);

ALTER TABLE INGREDIENTEPRODUCCION ADD CONSTRAINT FK_COMPOSICIONPRODUCTO     FOREIGN KEY (IDCOMPOSICIONPRODUCTO)     REFERENCES COMPOSICIONPRODUCTO (IDCOMPOSICIONPRODUCTO);
ALTER TABLE INGREDIENTEPRODUCCION ADD CONSTRAINT FK_METAPRODUCTOPRODUCCION  FOREIGN KEY (IDMETAPRODUCTOPRODUCCION)  REFERENCES METAPRODUCTOPRODUCCION (IDMETAPRODUCTOPRODUCCION);
                                                                


UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.idrhmarcado)/10+1 FROM rhmarcado E) WHERE TABLA='rhmarcado';


-- 08/03/2015

ALTER TABLE GESTIONIMPUESTO ADD CONSTRAINT PK_GESTIONIMPUESTO PRIMARY KEY (IDGESTIONIMPUESTO)

ALTER TABLE IMPUESTOPRODUCTOR ADD CONSTRAINT PK_IMPUESTOPRODUCTOR       PRIMARY KEY (IDIMPUESTOPRODUCTOR)
ALTER TABLE IMPUESTOPRODUCTOR ADD CONSTRAINT FK_PRODUCTORMATERIAPRIMA   FOREIGN KEY (IDPRODUCTORMATERIAPRIMA)   REFERENCES PRODUCTORMATERIAPRIMA(IDPRODUCTORMATERIAPRIMA)
ALTER TABLE IMPUESTOPRODUCTOR ADD CONSTRAINT FK_GESTIONIMPUESTO         FOREIGN KEY (IDGESTIONIMPUESTO)         REFERENCES gestionimpuesto(IDGESTIONIMPUESTO)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.idimpuestoproductor)/10+1 FROM impuestoproductor E) WHERE TABLA='impuestoproductor'


ALTER TABLE PRODUCTORMATERIAPRIMA ADD CONSTRAINT PK_PRODUCTORMATERIAPRIMA PRIMARY KEY (IDPRODUCTORMATERIAPRIMA)
ALTER TABLE PRODUCTORMATERIAPRIMA ADD CONSTRAINT FK_ZONAPRODUCTIVA     FOREIGN KEY (IDZONAPRODUCTIVA)     REFERENCES ZONAPRODUCTIVA (IDZONAPRODUCTIVA)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDPRODUCTORMATERIAPRIMA)/10+1 FROM PRODUCTORMATERIAPRIMA E) WHERE TABLA='PRODUCTORMATERIAPRIMA'


ALTER TABLE ZONAPRODUCTIVA ADD CONSTRAINT PK_ZONAPRODUCTIVA PRIMARY KEY (IDZONAPRODUCTIVA)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDRHMARCADO)/10+1 FROM RHMARCADO E) WHERE TABLA='rhmarcado'


-- 14/03/2015

ALTER TABLE RHMARCADO ADD CONSTRAINT PK_RHMARCADO PRIMARY KEY (IDRHMARCADO)

-- 18/03/2015
ALTER TABLE COMPANIA ADD CONSTRAINT PK_COMPANIA PRIMARY KEY (IDCOMPANIA)

ALTER TABLE DIRECCION ADD CONSTRAINT PK_DIRECCION           PRIMARY KEY (IDDIRECCION)
ALTER TABLE DIRECCION ADD CONSTRAINT FK_COMPANIADIRECCION   FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE DIRECCION ADD CONSTRAINT FK_CALLEDIRECCION      FOREIGN KEY (IDCALLE)       REFERENCES CALLE (IDCALLE)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDDIRECCION)/10+1 FROM DIRECCION E) WHERE TABLA='direccion'

ALTER TABLE CALLE ADD CONSTRAINT PK_CALLE           PRIMARY KEY (IDCALLE)
ALTER TABLE CALLE ADD CONSTRAINT FK_COMPANIACALLE   FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE CALLE ADD CONSTRAINT FK_BARRIOCALLE     FOREIGN KEY (IDBARRIO)      REFERENCES BARRIO (IDBARRIO)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDCALLE)/10+1 FROM CALLE E) WHERE TABLA='calle'

ALTER TABLE BARRIO ADD CONSTRAINT PK_BARRIO         PRIMARY KEY (IDBARRIO)
ALTER TABLE BARRIO ADD CONSTRAINT FK_COMPANIABARRIO FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE BARRIO ADD CONSTRAINT FK_ZONABARRIO     FOREIGN KEY (IDZONA)        REFERENCES ZONA (IDZONA)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDBARRIO)/10+1 FROM BARRIO E) WHERE TABLA='barrio'

ALTER TABLE ZONA ADD CONSTRAINT PK_ZONA             PRIMARY KEY (IDZONA)
ALTER TABLE ZONA ADD CONSTRAINT FK_COMPANIAZONA     FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE ZONA ADD CONSTRAINT FK_CIUDADZONA       FOREIGN KEY (IDCIUDAD)      REFERENCES CIUDAD   (IDCIUDAD)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDZONA)/10+1 FROM ZONA E) WHERE TABLA='zona'

ALTER TABLE CIUDAD ADD CONSTRAINT PK_CIUDAD                 PRIMARY KEY (IDCIUDAD)
ALTER TABLE CIUDAD ADD CONSTRAINT FK_COMPANIACIUDAD         FOREIGN KEY (IDCOMPANIA)        REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE CIUDAD ADD CONSTRAINT FK_DEPARTAMENTOCIUDAD     FOREIGN KEY (IDDEPARTAMENTO)    REFERENCES DEPARTAMENTO (IDDEPARTAMENTO)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDCIUDAD)/10+1 FROM CIUDAD E) WHERE TABLA='ciudad'

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_DEPARTAMENTO             PRIMARY KEY (IDDEPARTAMENTO)
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_COMPANIADEPARTAMENTO     FOREIGN KEY (IDCOMPANIA)        REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_PAISDEPARTAMENTO         FOREIGN KEY (IDPAIS)            REFERENCES PAIS (IDPAIS)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDDEPARTAMENTO)/10+1 FROM DEPARTAMENTO E) WHERE TABLA='departamento'

ALTER TABLE PAIS ADD CONSTRAINT PK_PAIS     PRIMARY KEY (IDPAIS)
ALTER TABLE PAIS ADD CONSTRAINT FK_COMPANIA FOREIGN KEY (IDCOMPANIA)     REFERENCES COMPANIA (IDCOMPANIA)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDPAIS)/10+1 FROM PAIS E) WHERE TABLA='pais'

--

ALTER TABLE TIPODOCUMENTO ADD CONSTRAINT PK_TIPODOCUMENTO           PRIMARY KEY (IDTIPODOCUMENTO)
ALTER TABLE TIPODOCUMENTO ADD CONSTRAINT FK_COMPANIATIPODOCUMENTO   FOREIGN KEY (IDCOMPANIA)     REFERENCES COMPANIA (IDCOMPANIA)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDTIPODOCUMENTO)/10+1 FROM TIPODOCUMENTO E) WHERE TABLA='tipodocumento'

ALTER TABLE EXTTIPODOCUMENTO ADD CONSTRAINT PK_EXTTIPODOCUMENTO           PRIMARY KEY (IDEXTTIPODOCUMENTO)
ALTER TABLE EXTTIPODOCUMENTO ADD CONSTRAINT FK_COMPANIAEXTTIPODOCUMENTO   FOREIGN KEY (IDCOMPANIA)        REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE EXTTIPODOCUMENTO ADD CONSTRAINT FK_TIPODOCUMENTOEXTTIPODOC    FOREIGN KEY (IDTIPODOCUMENTO)   REFERENCES TIPODOCUMENTO (IDTIPODOCUMENTO)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDEXTTIPODOCUMENTO)/10+1 FROM EXTTIPODOCUMENTO E) WHERE TABLA='EXTTIPODOCUMENTO'

ALTER TABLE ENTIDAD ADD CONSTRAINT PK_ENTIDAD                   PRIMARY KEY (IDENTIDAD)
ALTER TABLE ENTIDAD ADD CONSTRAINT FK_COMPANIAENTIDAD           FOREIGN KEY (IDCOMPANIA)            REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE ENTIDAD ADD CONSTRAINT FK_DIRECCIONENTIDAD          FOREIGN KEY (IDDIRECCION)           REFERENCES DIRECCION (IDDIRECCION)
ALTER TABLE ENTIDAD ADD CONSTRAINT FK_TIPODOCUMENTOENTIDAD      FOREIGN KEY (IDTIPODOCUMENTO)       REFERENCES TIPODOCUMENTO (IDTIPODOCUMENTO)
ALTER TABLE ENTIDAD ADD CONSTRAINT FK_EXTTIPODOCUMENTOENTIDAD   FOREIGN KEY (IDEXTTIPODOCUMENTO)    REFERENCES EXTTIPODOCUMENTO (IDEXTTIPODOCUMENTO)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDENTIDAD)/10+1 FROM ENTIDAD E) WHERE TABLA='entidad'

--

ALTER TABLE ESTADOCIVIL ADD CONSTRAINT PK_ESTADOCIVIL               PRIMARY KEY (IDESTADOCIVIL)
ALTER TABLE ESTADOCIVIL ADD CONSTRAINT FK_COMPANIAESTADOCIVIL       FOREIGN KEY (IDCOMPANIA)            REFERENCES COMPANIA (IDCOMPANIA)

ALTER TABLE SALUDO ADD CONSTRAINT PK_SALUDO               PRIMARY KEY (IDSALUDO)
ALTER TABLE SALUDO ADD CONSTRAINT FK_COMPANIASALUDO       FOREIGN KEY (IDCOMPANIA)            REFERENCES COMPANIA (IDCOMPANIA)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDSALUDO)/10+1 FROM SALUDO E) WHERE TABLA='saludo'

ALTER TABLE PERSONA ADD CONSTRAINT PK_PERSONA               PRIMARY KEY (IDPERSONA)
ALTER TABLE PERSONA ADD CONSTRAINT FK_COMPANIAPERSONA       FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE PERSONA ADD CONSTRAINT FK_PAISPERSONA           FOREIGN KEY (IDPAIS)        REFERENCES PAIS (IDPAIS)
ALTER TABLE PERSONA ADD CONSTRAINT FK_ESTADOCIVILPERSONA    FOREIGN KEY (IDESTADOCIVIL) REFERENCES ESTADOCIVIL (IDESTADOCIVIL)
ALTER TABLE PERSONA ADD CONSTRAINT FK_SALUDOPERSONA         FOREIGN KEY (IDSALUDO)      REFERENCES SALUDO (IDSALUDO)

--


ALTER TABLE TIPOUNIDADNEGOCIO ADD CONSTRAINT PK_TIPOUNIDADNEGOCIO               PRIMARY KEY (IDTIPOUNIDADNEGOCIO)
ALTER TABLE TIPOUNIDADNEGOCIO ADD CONSTRAINT FK_COMPANIATIPOUNIDADNEGOCIO       FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDTIPOUNIDADNEGOCIO)/10+1 FROM TIPOUNIDADNEGOCIO E) WHERE TABLA='tipounidadnegocio'

ALTER TABLE UNIDADNEGOCIO ADD CONSTRAINT PK_UNIDADNEGOCIO               PRIMARY KEY (IDUNIDADNEGOCIO)
ALTER TABLE UNIDADNEGOCIO ADD CONSTRAINT FK_COMPANIAUNIDADNEGOCIO       FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE UNIDADNEGOCIO ADD CONSTRAINT FK_TIPOUNIDADNEGOCIOUNIDADNEG  FOREIGN KEY (IDTIPOUNIDADNEGOCIO)    REFERENCES TIPOUNIDADNEGOCIO (IDTIPOUNIDADNEGOCIO)
ALTER TABLE UNIDADNEGOCIO ADD CONSTRAINT FK_EMPLEADOUNIDADNEGOCIO       FOREIGN KEY (IDRESPONSABLERH)        REFERENCES EMPLEADO (IDEMPLEADO)


ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO               PRIMARY KEY (IDEMPLEADO)
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_COMPANIAEMPLEADO       FOREIGN KEY (IDCOMPANIA)      REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_UNIDADNEGOCIOEMPLEADO  FOREIGN KEY (IDUNIDADNEGOCIO) REFERENCES UNIDADNEGOCIO (IDUNIDADNEGOCIO)


ALTER TABLE INSTITUCION ADD CONSTRAINT PK_INSTITUCION PRIMARY KEY (IDINSTITUCION)
ALTER TABLE INSTITUCION ADD CONSTRAINT FK_COMPANIAINSTITUCION FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)

-- 19/03/2015

ALTER TABLE NIVELORGANIZACIONAL ADD CONSTRAINT PK_NIVELORGANIZACIONAL PRIMARY KEY (IDNIVELORGANIZACIONAL)
ALTER TABLE NIVELORGANIZACIONAL ADD CONSTRAINT FK_COMPANIANIVELORGANIZACIONAL FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE NIVELORGANIZACIONAL ADD CONSTRAINT FK_NIVELORGANIZACIONALNIVELORG FOREIGN KEY (NIVELORGANIZACIONALRAIZ)    REFERENCES NIVELORGANIZACIONAL (IDNIVELORGANIZACIONAL)



ALTER TABLE SECTOR ADD CONSTRAINT PK_SECTOR PRIMARY KEY (IDSECTOR)
ALTER TABLE SECTOR ADD CONSTRAINT FK_COMPANIASECTOR FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDSECTOR)/10+1 FROM SECTOR E) WHERE TABLA='sector'

ALTER TABLE UNIDADORGANIZACIONAL ADD CONSTRAINT PK_UNIDADORGANIZACIONAL     PRIMARY KEY (IDUNIDADORGANIZACIONAL)
ALTER TABLE UNIDADORGANIZACIONAL ADD CONSTRAINT FK_COMPANIAUNIDADORG        FOREIGN KEY (IDCOMPANIA)                REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE UNIDADORGANIZACIONAL ADD CONSTRAINT FK_NIVELORGANIZACIONALUO    FOREIGN KEY (IDNIVELORGANIZACIONAL)     REFERENCES NIVELORGANIZACIONAL (IDNIVELORGANIZACIONAL)
ALTER TABLE UNIDADORGANIZACIONAL ADD CONSTRAINT FK_UNIDADORGANIZACIONALUO   FOREIGN KEY (UNIDADORGANIZACIONALRAIZ)  REFERENCES UNIDADORGANIZACIONAL (IDUNIDADORGANIZACIONAL)
ALTER TABLE UNIDADORGANIZACIONAL ADD CONSTRAINT FK_SECTORUNIDADORG          FOREIGN KEY (IDSECTOR)                  REFERENCES SECTOR (IDSECTOR)

UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDUNIDADORGANIZACIONAL)/10+1 FROM UNIDADORGANIZACIONAL E) WHERE TABLA='unidadorganizacional'

--


ALTER TABLE LIMITE ADD CONSTRAINT PK_LIMITE PRIMARY KEY (IDLIMITE)
ALTER TABLE LIMITE ADD CONSTRAINT FK_COMPANIALIMITE FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)

ALTER TABLE TOLERANCIA ADD CONSTRAINT PK_TOLERANCIA PRIMARY KEY (IDTOLERANCIA)
ALTER TABLE TOLERANCIA ADD CONSTRAINT FK_COMPANIATOLERANCIA FOREIGN KEY (IDCOMPANIA)    REFERENCES COMPANIA (IDCOMPANIA)

ALTER TABLE CATEGORIAPUESTO ADD CONSTRAINT PK_CATEGORIAPUESTO PRIMARY KEY (IDCATEGORIAPUESTO)
ALTER TABLE CATEGORIAPUESTO ADD CONSTRAINT FK_COMPANIACATEGORIAPUESTO FOREIGN KEY (IDCOMPANIA)  REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE CATEGORIAPUESTO ADD CONSTRAINT FK_SECTORCATEGORIAPUESTO FOREIGN KEY (IDSECTOR)      REFERENCES SECTOR (IDSECTOR)
ALTER TABLE CATEGORIAPUESTO ADD CONSTRAINT FK_LIMITECATEGORIAPUESTO     FOREIGN KEY (IDLIMITE)      REFERENCES LIMITE (IDLIMITE)
ALTER TABLE CATEGORIAPUESTO ADD CONSTRAINT FK_TOLERANCIACATEGORIAPUESTO FOREIGN KEY (IDTOLERANCIA)  REFERENCES TOLERANCIA (IDTOLERANCIA)

-- 20/03/2015

ALTER TABLE MODALIDADCONTRATO ADD CONSTRAINT PK_MODALIDADCONTRATO PRIMARY KEY (IDMODALIDADCONTRATO)
ALTER TABLE MODALIDADCONTRATO ADD CONSTRAINT FK_COMPANIAMODALIDADCONTRATO FOREIGN KEY (IDCOMPANIA)  REFERENCES COMPANIA (IDCOMPANIA)

ALTER TABLE ESTADOCONTRATO ADD CONSTRAINT PK_ESTADOCONTRATO PRIMARY KEY (IDESTADOCONTRATO)
ALTER TABLE ESTADOCONTRATO ADD CONSTRAINT FK_COMPANIAESTADOCONTRATO FOREIGN KEY (IDCOMPANIA)  REFERENCES COMPANIA (IDCOMPANIA)


ALTER TABLE CARGO ADD CONSTRAINT PK_CARGO PRIMARY KEY (IDCARGO)
ALTER TABLE CARGO ADD CONSTRAINT FK_COMPANIACARGO FOREIGN KEY (IDCOMPANIA)  REFERENCES COMPANIA (IDCOMPANIA)


ALTER TABLE TIPOSUELDO ADD CONSTRAINT PK_TIPOSUELDO PRIMARY KEY (IDTIPOSUELDO)
ALTER TABLE TIPOSUELDO ADD CONSTRAINT FK_COMPANIATIPOSUELDO FOREIGN KEY (IDCOMPANIA)  REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE TIPOSUELDO ADD CONSTRAINT FK_SECTORTIPOSUELDO FOREIGN KEY (IDSECTOR)  REFERENCES SECTOR (IDSECTOR)


ALTER TABLE TIPOCICLO ADD CONSTRAINT PK_TIPOCICLO PRIMARY KEY (IDTIPOCICLO)
ALTER TABLE TIPOCICLO ADD CONSTRAINT FK_COMPANIATIPOCICLO FOREIGN KEY (IDCOMPANIA)  REFERENCES COMPANIA (IDCOMPANIA)
ALTER TABLE TIPOCICLO ADD CONSTRAINT FK_SECTORTIPOCICLO FOREIGN KEY (IDSECTOR)  REFERENCES SECTOR (IDSECTOR)


ALTER TABLE CICLO ADD CONSTRAINT PK_CICLO PRIMARY KEY (IDCICLO)
ALTER TABLE CICLO ADD CONSTRAINT FK_COMPANIACICLO FOREIGN KEY (IDCOMPANIA)  REFERENCES COMPANIA (IDCOMPANIA)

-- ---------------------------------------------------------------------

-- 06/05/2015

ALTER TABLE sesionacopio ADD CONSTRAINT fk_metaproductopsesionacopio FOREIGN KEY (idmetaproductoproduccion) REFERENCES metaproductoproduccion (idmetaproductoproduccion);
ALTER TABLE sesionacopio ADD CONSTRAINT fk_zonaproductivasesionacopio FOREIGN KEY (idzonaproductiva)  	    REFERENCES zonaproductiva (idzonaproductiva);
ALTER TABLE sesionacopio ADD CONSTRAINT fk_companiasesionacopio FOREIGN KEY (idcompania)  	    	    REFERENCES compania (idcompania);


ALTER TABLE acopiomateriaprima ADD CONSTRAINT fk_productormateriaprimaacopiomateriaprima FOREIGN KEY (idproductormateriaprima) REFERENCES productormateriaprima (idproductormateriaprima);
ALTER TABLE acopiomateriaprima ADD CONSTRAINT fk_sesionacopioacopiomateriaprima FOREIGN KEY (idsesionacopio) REFERENCES sesionacopio (idsesionacopio);
ALTER TABLE acopiomateriaprima ADD CONSTRAINT fk_companiaacopiomateriaprima FOREIGN KEY (idcompania)  	    	    REFERENCES compania (idcompania);

-- 29/05/2015

ALTER TABLE sf_tmpdet ADD CONSTRAINT fk_tmpenc_tmpdet FOREIGN KEY (no_trans) REFERENCES sf_tmpenc (no_trans);


RECEPCIÓN, RECEPCION, ALMACEN (ALM PRODUCTOS TERMINADOS), ARTICULOS(118), FECHA(17/05/2015), APROBACIÓN DEL VALE NRO. 2-2(VALE GENERADO AUTOMÁTICAMENTE POR LA RECEPCIÓN DE LA ORDEN DE PRODUCCION NRO. : 1505-0125)
RECEPCIÓN, RECEPCION, ALMACEN (ALM PRODUCTOS TERMINADOS), ARTICULOS(118), FECHA(17/05/2015), APROBACIÓN DEL VALE NRO. 2-2(VALE GENERADO AUTOMÁTICAMENTE POR LA RECEPCIÓN DE LA ORDEN DE PRODUCCION NRO. : 1505-0125)