-- --------------------------------------------------
-- LISTA DE MARCACIONES POR MES
-- --------------------------------------------------
SELECT  E.IDENTIDAD, RH.MARPERID AS CI, 
        EM.CODIGOEMPLEADO,
        EM.CODIGOMARCACION,
        P.APELLIDOPATERNO, 
        P.APELLIDOMATERNO, 
        P.NOMBRES, 
        --TO_CHAR(RH.MARFECHA, 'DD/MM/YYYY') AS FECHA0, 
        TO_CHAR(RH.MARHORA, 'DD/MM/YYYY') AS FECHA, 
        TO_CHAR(RH.MARHORA, 'HH24:MI:SS') AS HORA
        -- RH.MARHORA  
FROM VMARCADO RH
JOIN ENTIDAD E   ON RH.MARPERID = E.NOIDENTIFICACION
JOIN PERSONA P   ON E.IDENTIDAD = P.IDPERSONA
JOIN EMPLEADO EM ON P.IDPERSONA = EM.IDEMPLEADO
WHERE RH.MARFECHA BETWEEN to_date('01/03/2015', 'DD/MM/YYYY') AND TO_DATE('30/11/2014','DD/MM/YYYY') 
ORDER BY RH.MARPERID, RH.MARFECHA, RH.MARHORA


-- -------------------------------------
-- --------------------------------------------------
-- LISTA DE MARCACIONES POR MES
-- --------------------------------------------------
SELECT  E.IDENTIDAD, RH.MARPERID AS CI, 
        EM.CODIGOEMPLEADO,
        EM.CODIGOMARCACION,
        P.APELLIDOPATERNO, 
        P.APELLIDOMATERNO, 
        P.NOMBRES, 
        RH.MARFECHA,
        TO_CHAR(RH.MARHORA, 'HH24:MI:SS') AS HORA,
        RH.MARHORA,
        RH.DESCRIPCION  
FROM RHMARCADO RH
JOIN ENTIDAD E   ON RH.MARREFTARJETA = E.NOIDENTIFICACION
JOIN PERSONA P   ON E.IDENTIDAD = P.IDPERSONA
JOIN EMPLEADO EM ON P.IDPERSONA = EM.IDEMPLEADO
WHERE RH.MARFECHA BETWEEN to_date('01/04/2015', 'DD/MM/YYYY') AND TO_DATE('30/04/2015','DD/MM/YYYY') 
ORDER BY RH.MARPERID, RH.MARFECHA, RH.MARHORA;

-- ----------------------------
-- QUERY OFICIAL
-- ----------------------------
SELECT  E.IDENTIDAD, 
        E.NOIDENTIFICACION AS CI, 
        -- EM.CODIGOEMPLEADO,
        EM.CODIGOMARCACION,
        P.APELLIDOPATERNO, 
        P.APELLIDOMATERNO, 
        P.NOMBRES, 
        RH.MARFECHA,
        RH.MARHORA
        -- RH.DESCRIPCION
FROM RHMARCADO RH
JOIN EMPLEADO EM ON RH.MARREFTARJETA = EM.CODIGOMARCACION
JOIN PERSONA P   ON EM.IDEMPLEADO    = P.IDPERSONA
JOIN ENTIDAD E   ON P.IDPERSONA      = E.IDENTIDAD
WHERE RH.MARFECHA BETWEEN '2018-10-01' AND '2018-10-31'
;


-- UPDATE SECUENCIA SET VALOR=(SELECT MAX(E.IDRHMARCADO)/10+1 FROM RHMARCADO E) WHERE TABLA='rhmarcado';
SELECT MAX(E.IDRHMARCADO)+1 FROM RHMARCADO E;




-- INSERT INTO rh_marcado (control, marfecha, marippc, marperid, marhora)
SELECT 0 AS control, r.`marfecha`, r.`marippc`, r.`marperid`, r.`marhora`
FROM rhmarcado r
WHERE r.`marfecha` BETWEEN '2018-07-01' AND '2018-07-31'
;

SELECT *
FROM vmarcado v
WHERE v.`marfecha` BETWEEN '2019-01-01' AND '2019-01-31'
;

-- DIAS PARA PASAJES
SELECT v.`marperid` AS CI, v.`nombre`, COUNT( DISTINCT DAY(v.`marfecha`) ) AS dias
FROM vmarcado v
WHERE v.`marfecha` BETWEEN '2018-12-01' AND '2018-12-31'
AND v.`marreftarjeta` IN (8714155,5283781,8048438,4532545,5264949,5924127)
GROUP BY v.`marperid`, v.`nombre`
;
