SELECT p.`IDPEDIDOS`, p.`FECHA_PEDIDO`, p.`FECHA_ENTREGA`, p.`ESTADO`, p.`TOTALIMPORTE`, p.`VALORCOMISION`, p.`CODIGO`, m.`IDMOVIMIENTO`, m.`NROFACTURA`, m.`IMPORTE_TOTAL`
FROM pedidos p
JOIN movimiento m ON p.`IDMOVIMIENTO` = m.`IDMOVIMIENTO`
WHERE p.`FECHA_ENTREGA` BETWEEN '2016-01-01' AND '2016-02-05'
AND p.`IDMOVIMIENTO` IS NOT NULL
;

SELECT *
FROM movimiento m
JOIN pedidos p ON m.`IDMOVIMIENTO` = p.`IDMOVIMIENTO`
WHERE p.`FECHA_ENTREGA` BETWEEN '2016-01-01' AND '2016-02-05'
;

-- ACTUALIZANDO IDPEDIDOS EN MOVIMIENTO
UPDATE movimiento m
JOIN pedidos p ON m.`IDMOVIMIENTO` = p.`IDMOVIMIENTO`
SET m.`IDPEDIDOS` = p.`IDPEDIDOS`
WHERE p.`FECHA_ENTREGA` BETWEEN '2016-01-01' AND '2016-02-05'
;


SELECT *
FROM movimiento m
JOIN ventadirecta v ON m.`IDMOVIMIENTO` = v.`IDMOVIMIENTO`
WHERE v.`FECHA_PEDIDO` BETWEEN '2016-01-01' AND '2016-02-05'
;

-- ACTUALIZANDO IDVENTADIRECTA EN MOVIMIENTO
UPDATE movimiento m
JOIN ventadirecta v ON m.`IDMOVIMIENTO` = v.`IDMOVIMIENTO`
SET m.`IDVENTADIRECTA` = v.`IDVENTADIRECTA`
WHERE v.`FECHA_PEDIDO` BETWEEN '2016-01-01' AND '2016-02-05'
;

-- ELIMINANDO REGISTROS DE MOVIMIENTO 

UPDATE ventadirecta SET IDMOVIMIENTO = NULL
WHERE IDVENTADIRECTA = 6
;

UPDATE ventadirecta SET IDMOVIMIENTO = NULL
WHERE IDVENTADIRECTA = 10
;

SELECT IDMOVIMIENTO
-- DELETE FROM movimiento
WHERE IDMOVIMIENTO <= 115
;


SELECT *
FROM movimiento_x
UPDATE movimiento_x SET IDPEDIDOS = NULL
WHERE IDPEDIDOS = 0
;

SELECT *
FROM movimiento_x
-- update movimiento_x set IDVENTADIRECTA = null
WHERE IDVENTADIRECTA = 0
;


-- ACTUALIZANDO RAZON SOCIAL EN MOVIMIENTO (PEDIDOS)
SELECT m.`FECHA_FACTURA`, m.`NROFACTURA`, c.`RAZONSOCIAL`
FROM movimiento_x m
JOIN pedidos p ON m.`IDPEDIDOS` = p.`IDPEDIDOS`
JOIN personacliente c ON p.`IDCLIENTE` = c.`IDPERSONACLIENTE`
WHERE m.`RAZON_SOCIAL` IS NULL
;
-- update movimiento_x m
JOIN pedidos p ON m.`IDPEDIDOS` = p.`IDPEDIDOS`
JOIN personacliente c ON p.`IDCLIENTE` = c.`IDPERSONACLIENTE`
SET m.`RAZON_SOCIAL` = c.`RAZONSOCIAL`
WHERE m.`RAZON_SOCIAL` IS NULL
;

-- ACTUALIZANDO RAZON SOCIAL EN MOVIMIENTO (VENTAS AL CONTADO)
SELECT m.`FECHA_FACTURA`, m.`NROFACTURA`, c.`RAZONSOCIAL`, v.`IDUSUARIO`, v.`IDVENTADIRECTA`
FROM movimiento_x m
JOIN ventadirecta v ON m.`IDVENTADIRECTA` = v.`IDVENTADIRECTA`
JOIN personacliente c ON v.`IDCLIENTE` = c.`IDPERSONACLIENTE`
WHERE m.`RAZON_SOCIAL` IS NULL
AND v.`IDUSUARIO` = 4
;
-- USUARIO 4
UPDATE movimiento_x m
JOIN ventadirecta v ON m.`IDVENTADIRECTA` = v.`IDVENTADIRECTA`
JOIN personacliente c ON v.`IDCLIENTE` = c.`IDPERSONACLIENTE`
SET m.`RAZON_SOCIAL` = c.`RAZONSOCIAL`
WHERE m.`RAZON_SOCIAL` IS NULL
AND v.`IDUSUARIO` = 4
;
-- USUARIO 5 CISC
-- UPDATE movimiento_x m
JOIN ventadirecta v ON m.`IDVENTADIRECTA` = v.`IDVENTADIRECTA`
JOIN personacliente c ON v.`IDCLIENTE` = c.`IDPERSONACLIENTE`
SET m.`RAZON_SOCIAL` = c.`RAZONSOCIAL`
WHERE m.`RAZON_SOCIAL` IS NULL
AND v.`IDUSUARIO` = 5
AND c.`IDPERSONACLIENTE` NOT IN (344, 356)
;
--

SELECT m.`FECHA_FACTURA`, m.`NROFACTURA`, c.`RAZONSOCIAL`, v.`IDUSUARIO`, v.`IDVENTADIRECTA`, c.`IDPERSONACLIENTE`
FROM movimiento_x m
JOIN ventadirecta v ON m.`IDVENTADIRECTA` = v.`IDVENTADIRECTA`
JOIN personacliente c ON v.`IDCLIENTE` = c.`IDPERSONACLIENTE`
WHERE m.`RAZON_SOCIAL` IS NULL
AND v.`IDUSUARIO` = 5
AND c.`IDPERSONACLIENTE` NOT IN (344, 356)
;






