SELECT *
FROM EOS.PLANIFICACIONPRODUCCION

SELECT *
FROM EOS.ORDENPRODUCCION;

SELECT P.FECHA, o.`idordenproduccion`, O.CODIGO, O.ESTADOORDEN
FROM ORDENPRODUCCION O
LEFT JOIN PLANIFICACIONPRODUCCION P ON O.IDPLANIFICACIONPRODUCCION = P.IDPLANIFICACIONPRODUCCION
WHERE P.FECHA BETWEEN '2015-07-14' AND '2015-07-14'
-- AND O.ESTADOORDEN <> 'TABULATED'
;

SELECT *
FROM WISE.SF_TMPENC T
WHERE T.FORMULARIO = 'ENTPRO'
AND T.FECHA BETWEEN TO_DATE('01/01/2014','DD/MM/YYYY') AND TO_DATE('31/01/2014','DD/MM/YYYY')
-- WHERE DESCRI LIKE '%1401-0135%'
;

SELECT *
FROM ordenproduccion
-- update ordenproduccion set estadoorden = 'EXECUTED'
WHERE idordenproduccion IN (
1212
)
;