SELECT p.`IDPEDIDOS`, p.`FECHA_PEDIDO`, p.`FECHA_ENTREGA`, p.`CODIGO`, p.`ESTADO`, p.`IDTIPOPEDIDO`, p.`TOTALIMPORTE`, p.`TIENEFACTURA`, p.`IDMOVIMIENTO`, m.`FECHA_FACTURA`, m.`NROFACTURA` -- p.`IDCLIENTE`, p.`id_tmpenc`
FROM pedidos p
LEFT JOIN movimiento m ON p.`IDMOVIMIENTO` = m.`IDMOVIMIENTO`
WHERE p.`FECHA_PEDIDO` BETWEEN '2017-05-08' AND '2017-05-08'
;

SELECT 'V' AS TIPO, v.`IDVENTADIRECTA` AS id, v.`FECHA_PEDIDO`, v.`FECHA_PEDIDO` AS FECHA_ENTREGA, v.`CODIGO`, v.`ESTADO`, NULL, v.`TOTALIMPORTE`, v.`IDMOVIMIENTO`, m.`FECHA_FACTURA`, m.`NROFACTURA`, v.`IDCLIENTE`, CONCAT(pe.`NOM`, pe.`AP`) AS NOMBRE
FROM ventadirecta v
LEFT JOIN movimiento m ON v.`IDMOVIMIENTO` = m.`IDMOVIMIENTO`
LEFT JOIN personacliente pe ON v.`IDCLIENTE` = pe.`IDPERSONACLIENTE`
WHERE v.`FECHA_PEDIDO` BETWEEN '2017-05-09' AND '2017-05-09'
;

--

SELECT 'P' AS TIPO, p.`IDPEDIDOS` AS id, p.`FECHA_PEDIDO`, p.`FECHA_ENTREGA`, p.`CODIGO`, p.`ESTADO`, p.`IDTIPOPEDIDO`, p.`TOTALIMPORTE`, p.`IDMOVIMIENTO`, m.`FECHA_FACTURA`, m.`NROFACTURA`, p.`IDCLIENTE`, CONCAT(pe.`NOM`, pe.`AP`) AS NOMBRE
FROM pedidos p
LEFT JOIN movimiento m ON p.`IDMOVIMIENTO` = m.`IDMOVIMIENTO`
LEFT JOIN personacliente pe ON p.`IDCLIENTE` = pe.`IDPERSONACLIENTE`
WHERE p.`FECHA_ENTREGA` BETWEEN '2017-05-08' AND '2017-05-11'
UNION ALL
SELECT 'V' AS TIPO, v.`IDVENTADIRECTA` AS id, v.`FECHA_PEDIDO`, v.`FECHA_PEDIDO` AS FECHA_ENTREGA, v.`CODIGO`, v.`ESTADO`, NULL, v.`TOTALIMPORTE`, v.`IDMOVIMIENTO`, m.`FECHA_FACTURA`, m.`NROFACTURA`, v.`IDCLIENTE`, CONCAT(pe.`NOM`, pe.`AP`) AS NOMBRE
FROM ventadirecta v
LEFT JOIN movimiento m ON v.`IDMOVIMIENTO` = m.`IDMOVIMIENTO`
LEFT JOIN personacliente pe ON v.`IDCLIENTE` = pe.`IDPERSONACLIENTE`
WHERE v.`FECHA_PEDIDO` BETWEEN '2017-05-08' AND '2017-05-11'
;

SELECT *
-- delete from movimiento 
WHERE IDMOVIMIENTO IN (

);


SELECT *
FROM pedidos p
UPDATE pedidos p SET p.`IDMOVIMIENTO` = NULL, p.`TIENEFACTURA` = 0, p.`IMPUESTO` = 0
WHERE p.`IDPEDIDOS` IN (

)
-- where p.`FECHA_ENTREGA` BETWEEN '2017-05-10' AND '2017-05-10'
;


SELECT *
FROM ventadirecta v
-- update ventadirecta v set v.`IDMOVIMIENTO` = null
WHERE v.`IDVENTADIRECTA` IN (

);

-- REPROTE DE VENTAS PEDIDOS ASIENTOS
SELECT p.`IDPEDIDOS`, p.`FECHA_ENTREGA`, p.`CODIGO`, p.`ESTADO`, p.`IDTIPOPEDIDO`, p.`TOTALIMPORTE`, p.`TIENEFACTURA`, p.`OBSERVACION`, p.`id_tmpenc`, e.`tipo_doc`, e.`no_doc`, e.`estado`
FROM pedidos p
LEFT JOIN sf_tmpenc e ON p.`id_tmpenc` = e.`id_tmpenc`
WHERE p.`IDCLIENTE` = 726
AND p.`FECHA_ENTREGA` BETWEEN '2017-04-01' AND '2017-04-30'
;

-- update pedidos p set p.`TIENEFACTURA` = 1, p.`ESTADO` = 'PREPARAR', p.`id_tmpenc` = null
WHERE p.`IDPEDIDOS` IN (

);

SELECT *
FROM sf_tmpenc
-- delete FROM sf_tmpenc
WHERE `id_tmpenc` IN (

);

SELECT *
FROM sf_tmpenc e
-- update sf_tmpenc e set e.`estado` = 'PEN'
WHERE e.`id_tmpenc` IN (

);

