SELECT * FROM COMPOSICIONPRODUCTO ORDER BY IDCOMPOSICIONPRODUCTO ASC

SELECT * FROM COMPOSICIONPRODUCTO 

SELECT * FROM INGREDIENTEPRODUCCION ORDER BY IDINGREDIENTEPRODUCCION

SELECT * FROM ORDENPRODUCCION

SELECT * FROM PLANIFICACIONPRODUCCION

SELECT * FROM VALEINSUMOSREQUERIDOS

SELECT * FROM VALEPRODUCTOTERMINADO


SELECT CP.PESOCONTENEDOR, PP.FECHA, OP.CODIGO, OP.PESOCONTENEDOR, MP.NOMBRE, IP.FORMULAMATEMATICA
FROM ORDENPRODUCCION OP
JOIN COMPOSICIONPRODUCTO CP         ON OP.IDCOMPOSICIONPRODUCTO     = CP.IDCOMPOSICIONPRODUCTO
JOIN INGREDIENTEPRODUCCION IP       ON CP.IDCOMPOSICIONPRODUCTO     = IP.IDCOMPOSICIONPRODUCTO
JOIN METAPRODUCTOPRODUCCION MP      ON IP.IDMETAPRODUCTOPRODUCCION  = MP.IDMETAPRODUCTOPRODUCCION
JOIN PLANIFICACIONPRODUCCION PP     ON OP.IDORDENPRODUCCION         = PP.IDPLANIFICACIONPRODUCCION
-- JOIN VALEINSUMOSREQUERIDOS VI       ON OP.IDORDENPRODUCCION         = VI.IDORDENPRODUCCION
-- WHERE CP.IDCOMPOSICIONPRODUCTO = 70


--

-- ALTER TABLE INGREDIENTEPRODUCCION ADD CONSTRAINT FK_INGREDIENTEP_COMPOSICIONP FOREIGN KEY (IDINGREDIENTEPRODUCCION) REFERENCES COMPOSICIONPRODUCTO (IDCOMPOSICIONPRODUCTO);

SELECT * FROM SECUENCIA WHERE TABLA LIKE 'INGREDIENTEPRODUCCION'

SELECT * FROM SECUENCIA WHERE TABLA LIKE 'COMPOSICIONPRODUCTO'


SELECT * FROM WISE.INV_ARTICULOS AR
WHERE AR.COD_GRU = 6

SELECT * FROM EOS.PRODUCTOPROCESADO

-- ALTER TABLE EOS.INGREDIENTEPRODUCCION
-- DROP CONSTRAINT FK_INGREDIENTEP_COMPOSICIONP;
