    
SELECT NN.MES, NN.NOMBRE, SUM(NN.LITROS) AS LITROS, NN.ACIDA, NN.AGUADABAJOSNG, NN.SUCIA, NN.CALOSTRO, NN.TACHOMALESTADO, NN.OTROS
FROM (    
    SELECT Z.NOMBRE, extract(month from N.FECHA) AS MES, /*N.FECHA,*/ N.CANTIDADRECHAZADA AS LITROS, N.ACIDA, N.AGUADABAJOSNG, N.SUCIA, N.CALOSTRO, N.TACHOMALESTADO, N.OTROS
    FROM EOS.NOTARECHAZOMATERIAPRIMA N, EOS.PRODUCTORMATERIAPRIMA P, EOS.ZONAPRODUCTIVA Z
    WHERE   N.IDPRODUCTORMATERIAPRIMA = P.IDPRODUCTORMATERIAPRIMA
    AND     P.IDZONAPRODUCTIVA        = Z.IDZONAPRODUCTIVA
) NN
WHERE NN.MES = 1
GROUP BY NN.MES, NN.NOMBRE, NN.ACIDA, NN.AGUADABAJOSNG, NN.SUCIA, NN.CALOSTRO, NN.TACHOMALESTADO, NN.OTROS


WHERE N.OTROS IS NOT NULL
-- AND N.IDNOTARECHAZOMATERIAPRIMA <> 100 

-- UPDATE EOS.NOTARECHAZOMATERIAPRIMA N SET N.ACIDA = 'ACIDA'
SELECT * FROM EOS.NOTARECHAZOMATERIAPRIMA N
WHERE N.ACIDA IS NOT NULL
AND N.IDNOTARECHAZOMATERIAPRIMA <> 100;


SELECT * FROM WISE.INV_VENTART
WHERE NO_FACT = 1
AND NO_CIA = 01
AND PEDIDO IS NULL



POSITIVO NEUTRALIZANTES (BICARBONATOS)


SELECT * FROM PRODUCTORMATERIAPRIMA
WHERE IDPRODUCTORMATERIAPRIMA = 552

SELECT * FROM PERSONA WHERE IDPERSONA = 552
