SELECT *
FROM ORDENPRODUCCION

SELECT *
FROM PLANIFICACIONPRODUCCION

SELECT * 
FROM PLANILLAACOPIO P
WHERE P.FECHA BETWEEN TO_DATE('01/03/2014','DD/MM/YYYY') AND TO_DATE('31/03/2014','DD/MM/YYYY')

SELECT *
FROM REGISTROACOPIO


SELECT P.FECHA, SUM(R.CANTIDADPESADA) AS TOTAL_PESADO
FROM REGISTROACOPIO R
LEFT JOIN PLANILLAACOPIO P ON R.IDPLANILLAACOPIO = P.IDPLANILLAACOPIO
WHERE P.FECHA BETWEEN TO_DATE('01/03/2014','DD/MM/YYYY') AND TO_DATE('31/03/2014','DD/MM/YYYY')
GROUP BY P.FECHA