-- desde pedidos
SELECT z.anio, z.mes, SUM(z.totalimporte) AS totalbs
FROM (
	SELECT YEAR(p.`FECHA_ENTREGA`) AS anio, MONTH(p.`FECHA_ENTREGA`) AS mes, p.`FECHA_ENTREGA` AS fecha, p.`TOTALIMPORTE`
	FROM pedidos p
	WHERE p.`ESTADO` <> 'ANULADO'
	AND P.`IDMOVIMIENTO` IS NOT NULL
	AND p.`FECHA_ENTREGA` BETWEEN '2016-01-01' AND '2018-12-31'
	UNION
	SELECT YEAR(v.`FECHA_PEDIDO`) AS anio, MONTH(v.`FECHA_PEDIDO`) AS mes, v.`FECHA_PEDIDO` AS fecha, v.`TOTALIMPORTE`
	FROM ventadirecta v 
	WHERE v.`ESTADO` <> 'ANULADO'
	AND v.`IDMOVIMIENTO` IS NOT NULL
	AND v.`FECHA_PEDIDO`  BETWEEN '2016-01-01' AND '2018-12-31'
) z
GROUP BY z.anio, z.mes
;


-- desde facturacion
SELECT z.anio, z.mes, SUM(z.importe_total) AS importe_total
FROM (
	SELECT YEAR(m.`FECHA_FACTURA`) AS anio, MONTH(m.`FECHA_FACTURA`) AS mes, m.`FECHA_FACTURA`, m.`IMPORTE_TOTAL`
	FROM movimiento m
	LEFT JOIN pedidos p ON m.`IDPEDIDOS` = p.`IDPEDIDOS`
	WHERE m.`FECHA_FACTURA` BETWEEN '2016-01-01' AND '2018-12-31'
	AND m.`ESTADO` <> 'A'
	AND p.`IDUSUARIO` <> 5
	UNION
	SELECT YEAR(m.`FECHA_FACTURA`) AS anio, MONTH(m.`FECHA_FACTURA`) AS mes, m.`FECHA_FACTURA`, m.`IMPORTE_TOTAL`
	FROM movimiento m
	LEFT JOIN ventadirecta v ON m.`IDVENTADIRECTA` = v.`IDVENTADIRECTA`
	WHERE m.`FECHA_FACTURA` BETWEEN '2016-01-01' AND '2018-12-31'
	AND m.`ESTADO` <> 'A'
	AND v.`IDUSUARIO` <> 5
) z
GROUP BY  z.anio, z.mes
;
